set_property PACKAGE_PIN F19 [get_ports {red[4]}]
set_property PACKAGE_PIN G20 [get_ports {red[3]}]
set_property PACKAGE_PIN J20 [get_ports {red[2]}]
set_property PACKAGE_PIN L20 [get_ports {red[1]}]
set_property PACKAGE_PIN M19 [get_ports {red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]
set_property PACKAGE_PIN F20 [get_ports {green[5]}]
set_property PACKAGE_PIN H20 [get_ports {green[4]}]
set_property PACKAGE_PIN J19 [get_ports {green[3]}]
set_property PACKAGE_PIN L19 [get_ports {green[2]}]
set_property PACKAGE_PIN N20 [get_ports {green[1]}]
set_property PACKAGE_PIN H18 [get_ports {green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {green[0]}]
set_property PACKAGE_PIN G19 [get_ports {blue[4]}]
set_property PACKAGE_PIN J18 [get_ports {blue[3]}]
set_property PACKAGE_PIN K19 [get_ports {blue[2]}]
set_property PACKAGE_PIN M20 [get_ports {blue[1]}]
set_property PACKAGE_PIN P20 [get_ports {blue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {blue[0]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]

set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN L16 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]

set_property PACKAGE_PIN D20 [get_ports ram_write_ok]
set_property IOSTANDARD LVCMOS33 [get_ports ram_write_ok]


set_property PACKAGE_PIN P16 [get_ports {button[1]}]
set_property PACKAGE_PIN R18 [get_ports {button[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]

set_property PACKAGE_PIN Y16 [get_ports reset_button]
set_property IOSTANDARD LVCMOS33 [get_ports reset_button]
