# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/VGA_project/VGA_project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_project || ORIG_REF_NAME==VGA_project} -quiet] -quiet

# IP: bd/VGA_project/ip/VGA_project_clk_wiz_0_0/VGA_project_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_project_clk_wiz_0_0 || ORIG_REF_NAME==VGA_project_clk_wiz_0_0} -quiet] -quiet

# IP: bd/VGA_project/ip/VGA_project_VGA_output_0_0/VGA_project_VGA_output_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_project_VGA_output_0_0 || ORIG_REF_NAME==VGA_project_VGA_output_0_0} -quiet] -quiet

# IP: bd/VGA_project/ip/VGA_project_Game_controller_0_0/VGA_project_Game_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_project_Game_controller_0_0 || ORIG_REF_NAME==VGA_project_Game_controller_0_0} -quiet] -quiet

# XDC: bd/VGA_project/VGA_project_ooc.xdc
